import Head from "next/head";
import { AuthForm } from "../../lib/auth/AuthForm";
import { VStack } from "../../lib/layout/VStack";

export interface HomePageProps {
}

export function HomePage({}: HomePageProps): JSX.Element {
  return (
    <div className="HomePage p-4">
      <Head>
        <title>My Tempo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack>
        <h1 className="text-3xl font-bold">My Tempo</h1>
        <AuthForm />
      </VStack>
    </div>
  );
}
